export type VisaStatus = {
  status: 'visa_free' | 'visa_on_arrival' | 'visa_required'
  duration?: string
  notes?: string
  embassyUrl?: string
}

// Keyed by [passport nationality] → [destination country] → VisaStatus
// Based on Henley Passport Index & official government sources (as of 2024-2025).
// Visa policies change — always direct users to verify with official sources.
const visaDb: Record<string, Record<string, VisaStatus>> = {

  // ─── Nigerian passport ───────────────────────────────────────────────────────
  Nigeria: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required', embassyUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required', embassyUrl: 'https://nigeria.diplo.de/ng-en/visaeinreise/visa' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required', embassyUrl: 'https://nigeria.ambafrance.org/Visa-et-passeport' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Belgium':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Sweden':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Norway':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Denmark':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Switzerland':        { status: 'visa_required', notes: 'Swiss national visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required', embassyUrl: 'https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada.html' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required', embassyUrl: 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/visitor-600' },
    'UAE':                { status: 'visa_required', notes: 'Visa required; e-visa available online', embassyUrl: 'https://smartservices.ica.gov.ae/echannels/web/client/guest/index.html' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required', embassyUrl: 'https://www.visaforchina.cn/' },
    'Japan':              { status: 'visa_required', notes: 'Temporary visitor visa required', embassyUrl: 'https://www.nigeria.emb-japan.go.jp/itpr_en/visa.html' },
    'Singapore':          { status: 'visa_required', notes: 'Visa required; apply online via ICA', embassyUrl: 'https://www.ica.gov.sg/enter-depart/entry_requirements/visa_requirements' },
    'South Korea':        { status: 'visa_required', notes: 'Visitor visa required' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required, apply at indianvisaonline.gov.in', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Malaysia':           { status: 'visa_required', notes: 'Visa required for most Nigerians' },
    'Thailand':           { status: 'visa_on_arrival', duration: '15 days', notes: 'Visa on arrival at major airports; eVisa also available' },
    'Rwanda':             { status: 'visa_free', duration: '30 days', notes: 'Visa-free for ECOWAS citizens' },
    'Kenya':              { status: 'visa_on_arrival', duration: '90 days', notes: 'eTA available; EAC partner-state arrangements' },
    'Tanzania':           { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival at international airports' },
    'Uganda':             { status: 'visa_on_arrival', duration: '90 days', notes: 'East Africa Tourist Visa option available' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at Bole International Airport' },
    'Ghana':              { status: 'visa_free', duration: '90 days', notes: 'ECOWAS freedom of movement' },
    'Senegal':            { status: 'visa_free', duration: '90 days', notes: 'ECOWAS freedom of movement' },
    'South Africa':       { status: 'visa_required', notes: 'South African visa required for Nigerians' },
    'Morocco':            { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at major international airports' },
    'Qatar':              { status: 'visa_required', notes: 'Visa required; apply via Qatar Visa Center' },
    'Netherlands (Antilles)': { status: 'visa_required', notes: 'Schengen visa required' },
  },

  // ─── Kenyan passport ─────────────────────────────────────────────────────────
  Kenya: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required', embassyUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Belgium':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Sweden':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Norway':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Denmark':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Switzerland':        { status: 'visa_required', notes: 'Swiss national visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available', embassyUrl: 'https://smartservices.ica.gov.ae/' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Temporary visitor visa required' },
    'Singapore':          { status: 'visa_required', notes: 'Visa required' },
    'South Korea':        { status: 'visa_required', notes: 'Visitor visa required' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply at indianvisaonline.gov.in', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Thailand':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at major airports' },
    'Rwanda':             { status: 'visa_free', duration: '30 days', notes: 'EAC partner state; eVisa also available' },
    'Tanzania':           { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Uganda':             { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at Bole International Airport' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '90 days', notes: 'e-Visa system' },
    'South Africa':       { status: 'visa_required', notes: 'South African visa required' },
    'Ghana':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Morocco':            { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available' },
    'Malaysia':           { status: 'visa_required', notes: 'Visa required' },
    'Qatar':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at Doha airport' },
  },

  // ─── Ghanaian passport ───────────────────────────────────────────────────────
  Ghana: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required', embassyUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Belgium':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Sweden':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Norway':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Switzerland':        { status: 'visa_required', notes: 'Swiss national visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_required', notes: 'Visa required; e-visa available' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Temporary visitor visa required' },
    'Singapore':          { status: 'visa_required', notes: 'Visa required' },
    'South Korea':        { status: 'visa_required', notes: 'Visitor visa required' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Thailand':           { status: 'visa_on_arrival', duration: '15 days', notes: 'Visa on arrival at major airports' },
    'Nigeria':            { status: 'visa_free', duration: '90 days', notes: 'ECOWAS freedom of movement' },
    'Senegal':            { status: 'visa_free', duration: '90 days', notes: 'ECOWAS freedom of movement' },
    'Rwanda':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Kenya':              { status: 'visa_on_arrival', duration: '90 days', notes: 'e-Visa available' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at Bole International Airport' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Morocco':            { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available' },
    'Qatar':              { status: 'visa_required', notes: 'Visa required' },
  },

  // ─── South African passport ──────────────────────────────────────────────────
  'South Africa': {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required', embassyUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Belgium':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Sweden':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Norway':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Denmark':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Switzerland':        { status: 'visa_required', notes: 'Swiss national visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_free', duration: '30 days', notes: 'Visa-free for South African passport holders' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required; check consulate' },
    'Singapore':          { status: 'visa_free', duration: '30 days', notes: 'Visa-free for tourism and business' },
    'South Korea':        { status: 'visa_required', notes: 'Visitor visa required' },
    'Brazil':             { status: 'visa_free', duration: '90 days', notes: 'Visa-free for tourism' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Thailand':           { status: 'visa_free', duration: '30 days', notes: 'Visa exemption for South African citizens' },
    'Kenya':              { status: 'visa_free', duration: '90 days', notes: 'Visa-free; eTA system' },
    'Rwanda':             { status: 'visa_free', duration: '30 days', notes: 'Visa-free; eVisa also available' },
    'Tanzania':           { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival available' },
    'Uganda':             { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival available' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival at Bole International Airport' },
    'Nigeria':            { status: 'visa_required', notes: 'Visa required' },
    'Morocco':            { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available' },
    'Qatar':              { status: 'visa_free', duration: '30 days', notes: 'Visa-free for South Africans' },
    'Malaysia':           { status: 'visa_free', duration: '30 days', notes: 'Social visit pass granted on arrival' },
  },

  // ─── Ethiopian passport ──────────────────────────────────────────────────────
  Ethiopia: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required', embassyUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Belgium':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_required', notes: 'Visa required' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Singapore':          { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Thailand':           { status: 'visa_on_arrival', duration: '15 days', notes: 'Visa on arrival at major airports' },
    'Kenya':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival; IGAD arrangement' },
    'Rwanda':             { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival; e-Visa available' },
    'Tanzania':           { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival' },
    'Uganda':             { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available' },
    'Morocco':            { status: 'visa_required', notes: 'Visa required' },
  },

  // ─── Ugandan passport ────────────────────────────────────────────────────────
  Uganda: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required', embassyUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Singapore':          { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Thailand':           { status: 'visa_on_arrival', duration: '15 days', notes: 'Visa on arrival at major airports' },
    'Kenya':              { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Rwanda':             { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Tanzania':           { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival available' },
  },

  // ─── Tanzanian passport ──────────────────────────────────────────────────────
  Tanzania: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_required', notes: 'Visa required' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Kenya':              { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Rwanda':             { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Uganda':             { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
  },

  // ─── Rwandan passport ────────────────────────────────────────────────────────
  Rwanda: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required', embassyUrl: 'https://travel.state.gov/content/travel/en/us-visas/tourism-visit.html' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Belgium':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Sweden':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_free', duration: '30 days', notes: 'Visa-free for Rwandan passport holders' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Singapore':          { status: 'visa_free', duration: '30 days', notes: 'Visa-free for short stays' },
    'South Korea':        { status: 'visa_required', notes: 'Visitor visa required' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Thailand':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Kenya':              { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Uganda':             { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Tanzania':           { status: 'visa_free', duration: '90 days', notes: 'EAC freedom of movement' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Ghana':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Morocco':            { status: 'visa_free', duration: '90 days', notes: 'Visa-free for Rwandan citizens' },
    'Senegal':            { status: 'visa_free', duration: '90 days', notes: 'AU free movement protocol' },
    'Mozambique':         { status: 'visa_free', duration: '30 days', notes: 'SADC arrangement' },
    'Zambia':             { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival' },
    'Qatar':              { status: 'visa_free', duration: '30 days', notes: 'Visa-free for Rwandan passport holders' },
    'Malaysia':           { status: 'visa_free', duration: '30 days', notes: 'Visa-free for short stays' },
  },

  // ─── Senegalese passport ─────────────────────────────────────────────────────
  Senegal: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_required', notes: 'Visa required' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Nigeria':            { status: 'visa_free', duration: '90 days', notes: 'ECOWAS freedom of movement' },
    'Ghana':              { status: 'visa_free', duration: '90 days', notes: 'ECOWAS freedom of movement' },
    'Rwanda':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Morocco':            { status: 'visa_free', duration: '90 days', notes: 'Bilateral visa-free agreement' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Kenya':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Tunisia':            { status: 'visa_free', duration: '90 days', notes: 'Bilateral agreement' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
    'Qatar':              { status: 'visa_required', notes: 'Visa required' },
  },

  // ─── Cameroonian passport ────────────────────────────────────────────────────
  Cameroon: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_required', notes: 'Visa required' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Rwanda':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Ethiopia':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Morocco':            { status: 'visa_required', notes: 'Visa required' },
    'Kenya':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Tanzania':           { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
  },

  // ─── Zimbabwean passport ─────────────────────────────────────────────────────
  Zimbabwe: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_required', notes: 'Visa required' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'South Africa':       { status: 'visa_free', duration: '30 days', notes: 'Visa-free for short visits' },
    'Kenya':              { status: 'visa_on_arrival', duration: '90 days', notes: 'e-Visa available' },
    'Rwanda':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Tanzania':           { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival; Kaza Univisa option' },
    'Zambia':             { status: 'visa_on_arrival', duration: '90 days', notes: 'Kaza Univisa (ZW-ZM joint visa)' },
    'Botswana':           { status: 'visa_free', duration: '30 days', notes: 'Visa-free; SADC arrangement' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
  },

  // ─── Zambian passport ────────────────────────────────────────────────────────
  Zambia: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'UAE':                { status: 'visa_required', notes: 'Visa required' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Kenya':              { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival' },
    'Rwanda':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Tanzania':           { status: 'visa_on_arrival', duration: '90 days', notes: 'Visa on arrival' },
    'South Africa':       { status: 'visa_free', duration: '30 days', notes: 'SADC arrangement' },
    'Zimbabwe':           { status: 'visa_on_arrival', duration: '90 days', notes: 'Kaza Univisa option' },
    'Botswana':           { status: 'visa_free', duration: '90 days', notes: 'SADC arrangement' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Egypt':              { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
  },

  // ─── Egyptian passport ───────────────────────────────────────────────────────
  Egypt: {
    'United Kingdom':     { status: 'visa_required', notes: 'Standard visitor visa required', embassyUrl: 'https://www.gov.uk/standard-visitor/apply-standard-visitor-visa' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival for Egyptian nationals' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available at evisa.gov.tr', embassyUrl: 'https://www.evisa.gov.tr/en/' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Jordan':             { status: 'visa_free', duration: '30 days', notes: 'Bilateral agreement' },
    'Morocco':            { status: 'visa_free', duration: '90 days', notes: 'Arab League member' },
    'Tunisia':            { status: 'visa_free', duration: '90 days', notes: 'Arab League member' },
    'Nigeria':            { status: 'visa_on_arrival', duration: '30 days', notes: 'Visa on arrival' },
    'Kenya':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'Rwanda':             { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa available' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Brazil':             { status: 'visa_required', notes: 'Tourist visa required' },
    'Singapore':          { status: 'visa_required', notes: 'Visa required' },
    'Malaysia':           { status: 'visa_required', notes: 'Visa required' },
  },

  // ─── Moroccan passport ───────────────────────────────────────────────────────
  Morocco: {
    'United Kingdom':     { status: 'visa_free', duration: '6 months', notes: 'Visa-free entry for Moroccan passport holders' },
    'United States':      { status: 'visa_required', notes: 'B-1/B-2 visitor visa required' },
    'Germany':            { status: 'visa_required', notes: 'Schengen visa required' },
    'France':             { status: 'visa_required', notes: 'Schengen visa required' },
    'Netherlands':        { status: 'visa_required', notes: 'Schengen visa required' },
    'Belgium':            { status: 'visa_required', notes: 'Schengen visa required' },
    'Spain':              { status: 'visa_required', notes: 'Schengen visa required' },
    'Portugal':           { status: 'visa_required', notes: 'Schengen visa required' },
    'Canada':             { status: 'visa_required', notes: 'Temporary Resident Visa required' },
    'Australia':          { status: 'visa_required', notes: 'Visitor visa required' },
    'UAE':                { status: 'visa_free', duration: '30 days', notes: 'Visa-free for Moroccan passport holders' },
    'China':              { status: 'visa_required', notes: 'Tourist visa required' },
    'Japan':              { status: 'visa_required', notes: 'Visa required' },
    'Turkey':             { status: 'visa_free', duration: '90 days', notes: 'Bilateral visa-free agreement' },
    'Brazil':             { status: 'visa_free', duration: '90 days', notes: 'Bilateral visa-free agreement' },
    'Senegal':            { status: 'visa_free', duration: '90 days', notes: 'Bilateral agreement' },
    'Tunisia':            { status: 'visa_free', duration: '90 days', notes: 'Maghreb agreement' },
    'Rwanda':             { status: 'visa_free', duration: '30 days', notes: 'Bilateral visa-free' },
    'Nigeria':            { status: 'visa_required', notes: 'Visa required' },
    'Egypt':              { status: 'visa_free', duration: '90 days', notes: 'Arab League arrangement' },
    'South Africa':       { status: 'visa_required', notes: 'Visa required' },
    'Qatar':              { status: 'visa_free', duration: '30 days', notes: 'Bilateral agreement' },
    'India':              { status: 'visa_on_arrival', duration: '30 days', notes: 'e-Visa required; apply online', embassyUrl: 'https://indianvisaonline.gov.in/evisa/tvoa.html' },
    'Malaysia':           { status: 'visa_free', duration: '90 days', notes: 'Visa-free short stays' },
  },
}

export function lookupVisa(nationality: string, country: string): VisaStatus | null {
  const byPassport = visaDb[nationality]
  if (!byPassport) return null
  return byPassport[country] ?? null
}

export { visaDb }
